// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNrbsuHSU3gP-ZPcgw_5jQI1OIBceBFC8',
    appId: '1:204078814910:web:3ca750aff5ca397c7a30ef',
    messagingSenderId: '204078814910',
    projectId: 'find-my-stuff-3928c',
    authDomain: 'find-my-stuff-3928c.firebaseapp.com',
    storageBucket: 'find-my-stuff-3928c.appspot.com',
    measurementId: 'G-CXL1G655Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tAWL0mr7h8dVEvKFnFSXsHWJUt93gbw',
    appId: '1:204078814910:android:9cf92c5cc1c7fce77a30ef',
    messagingSenderId: '204078814910',
    projectId: 'find-my-stuff-3928c',
    storageBucket: 'find-my-stuff-3928c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KMur0eS-k4hGXsasuxnrQqdUENr5iFE',
    appId: '1:204078814910:ios:062082795f735b597a30ef',
    messagingSenderId: '204078814910',
    projectId: 'find-my-stuff-3928c',
    storageBucket: 'find-my-stuff-3928c.appspot.com',
    iosClientId: '204078814910-opjt8a2g50hho08g6vkbj19kum47m343.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFindMyStuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KMur0eS-k4hGXsasuxnrQqdUENr5iFE',
    appId: '1:204078814910:ios:062082795f735b597a30ef',
    messagingSenderId: '204078814910',
    projectId: 'find-my-stuff-3928c',
    storageBucket: 'find-my-stuff-3928c.appspot.com',
    iosClientId: '204078814910-opjt8a2g50hho08g6vkbj19kum47m343.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFindMyStuff',
  );
}
